version: '3.8'

services:
  x-bot:
    build: .
    container_name: x-bot-ntf
    restart: unless-stopped
    environment:
      - DATA_PATH=/app/data
    volumes:
      # 掛載配置文件（需要在部署時創建）
      - ./configs.yml:/app/configs.yml:ro
      # 掛載數據目錄到宿主機，持久化資料庫
      - ./data:/app/data
      # 掛載環境變數文件（需要在部署時創建）
      - ./.env:/app/.env:ro
    networks:
      - bot-network
    # 可選：健康檢查
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0) if os.path.exists('/app/data/tracked_accounts.db') else exit(1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge

# 可選：如果需要日誌管理
volumes:
  bot-data:
    driver: local
